# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: local
  hooks:
    - id: formatter
      name: Format Elixir files
      files: ".*\\.exs?"
      language: system
      entry: "mix"
      args: ["format"]
    - id: credo
      name: Check style with Credo
      files: ".*\\.exs?"
      language: system
      entry: "mix"
      args: ["credo", "-a"]

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.4.0
  hooks:
    - id: no-commit-to-branch
      args: ["-b", "master", "-b", "develop", "-b", "main", "-b", "rc"]
    - id: check-merge-conflict
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml
    - id: check-added-large-files
